### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by leave8426** [bianjp/popup-dict#5]
Traceback (most recent call last):
  File "/usr/bin/popup-dict", line 7, in <module>
    from popupdict.main import main
  File "/usr/lib/python3.6/site-packages/popupdict/main.py", line 8, in <module>
    from .gtk import *
  File "/usr/lib/python3.6/site-packages/popupdict/gtk/__init__.py", line 7, in <module>
    Gst.init()
TypeError: init() missing 1 required positional argument: 'argv'

**Comment by bianjp** [comment]
`gstreamer` 版本号是多少?

**Comment by leave8426** [comment]
1.14.2-1

**Comment by bianjp** [comment]
有点奇怪，你执行这些语句看下输出：

```python
import gi
gi.require_version('Gst', '1.0')
from gi.repository import Gst
print(Gst._version)
print(Gst.version_string())
print(Gst.init.__doc__)
print([a.get_name() + ":" + str(a.is_optional()) for a in Gst.init.get_arguments()])
```

**Comment by leave8426** [comment]
1.0
Traceback (most recent call last):
  File "/home/leave8426/ACM/test.py", line 5, in <module>
    print(Gst.version_string())
  File "/usr/lib/python3.6/site-packages/gi/overrides/Gst.py", line 589, in fake_method
    raise NotInitialized("Please call Gst.init(argv) before using GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer

**Comment by leave8426** [comment]
Manjaro 17.1.7 GNOME
PyGoject : `sudo pacman -S python-gobject python2-gobject gtk3`
GStreamer : 作为另一个软件包的依赖而安装
Python 3.6.6.1 : 作为另一个软件包的依赖而安装

**Comment by bianjp** [comment]
我检查了下 Manjaro 的 `python-gobject` 包中并没有 `/usr/lib/python3.6/site-packages/gi/overrides/Gst.py` 这个文件。你看下这个文件是属于哪个包的：

```bash
pacman -Qo /usr/lib/python3.6/site-packages/gi/overrides/Gst.py
```

**Comment by leave8426** [comment]
/usr/lib/python3.6/site-packages/gi/overrides/Gst.py 由 gst-python 1.14.1-1 所拥有

**Comment by bianjp** [comment]
[gst-python](https://gstreamer.freedesktop.org/modules/gst-python.html) 由 GStreamer 官方团队维护，主页只是说 "overrides for the gobject-introspection-based pygst bindings" 却没说为什么要 override，也没说兼容性。

你可以暂时把 `gst-python` 卸载。我有空再好好考虑下是否有必要兼容 `gst-python`。

**Comment by bianjp** [comment]
[gst-python](https://gstreamer.freedesktop.org/modules/gst-python.html) 由 GStreamer 官方团队维护，主页只是说 "overrides for the gobject-introspection-based pygst bindings" 却没说为什么要 override，也没说兼容性。

你可以暂时把 `gst-python` 卸载。我有空再好好考虑下是否有必要兼容 `gst-python`。

**Comment by leave8426** [comment]
卸载后可以启动。THX
