### ISSUE TITLE
发音配置&popup_timeout似乎有Bug

### ISSUE THREAD

**Issue by leave8426** [bianjp/popup-dict#6]
发音配置
`[speech]`
启用发音
`enabled = true`
自动播放
`auto_play = false`
如上配置时，能正确查词，但仍然会自动播放

发音配置
`[speech]`
启用发音
`enabled = false`
自动播放
`auto_play = false`
这样配置时，大概查完一次词就会出错（命令行输出如下），不能继续查词，似乎没缓存的单词不会自动播放，有缓存的则会自动播放

`
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/popupdict/daemon/query.py", line 87, in run
    self.speech_adapter.remove_old_cache()
AttributeError: 'NoneType' object has no attribute 'remove_old_cache'
`

**Comment by leave8426** [comment]
popup_timeout似乎不起作用

**Comment by bianjp** [comment]
已经发布了新版本 v0.3.2，都修复了。
